[programs.localnet]
climax_controller = "3pqVVuz8ghE5LT4Z26xjPi17qqXLartUra8yMkABCeEG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "testnet"
#cluster = "devnet"
cluster = "localnet"
wallet = "/home/myware/.config/solana/mainnet.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/*.ts"
